<?php
namespace App\View;

use App\Model\Favorite;

include_once "application/database/DatabaseHandler.php";
include "application/class/models/Favorite.php";

$favorite = new Favorite();
?>

<div id="json_favorite_list" style="display: none;">
    <?php
    echo htmlspecialchars($favorite->getListOfFavorites());
    ?>
</div>

<div id="json_category_favorite_1" style="display: none;">
    <?php
    echo htmlspecialchars($favorite->getProductForCategory("car"));
    ?>
</div>

<div id="json_category_favorite_2" style="display: none;">
    <?php
    echo htmlspecialchars($favorite->getProductForCategory("bev"));
    ?>
</div>

<div id="json_category_favorite_3" style="display: none;">
    <?php
    echo htmlspecialchars($favorite->getProductForCategory("wat"));
    ?>
</div>
