<?php
namespace App\View;

/* @var string $maxUserId Next maximum User id */
/* @var bool $isAdmin User Flag for admin */

use App\Model\Login;
use App\Model\CustomSession;

const root = '/BackendRouting';

if(isset($_POST["submit"])){

    include "application/class/models/CustomSession.php";
    include_once "application/database/DatabaseHandler.php";
    include "application/class/controllers/LoginController.php";
    include "application/class/models/Login.php";

    // Getting data from login form
    $email = $_POST["email"];
    $userPwd = $_POST["password"];
    $login = new Login($email, $userPwd);

    if(($login->loginUser())){
       // setcookie('email', $email, time()+60*60*7);

        $sessions_handler = new CustomSession();

        if(!isset($_SESSION)) {
            session_set_save_handler($sessions_handler, true);
            session_name('MySessionName');
            session_start();

        }
        $_SESSION['isLogged'] = true;
        $_SESSION['email'] = $email;
        $_SESSION['userId'] = $maxUserId ?? null;
        $_SESSION['isAdmin'] = $isAdmin ?? false;
        $_SESSION['password'] = $userPwd;
        $sessions_handler->write( $_SESSION['userId'],session_id());

        session_write_close();

        // redirect to login page
        header("location: " . root . "/home");
    }else{
        header("location: " . root . "/login?error=failed");
    }
}