<?php
namespace App\View;

use App\Model\Signup;

const root = '/BackendRouting';

/* Accessing page only when form button is pressed
    "submit" = name of the button in signup page
    $_POST["..."] -> gets information from the form
*/
if(isset($_POST["signup"])) {
    // grabbing the data
    $uid= $_POST["uid"];
    $email= $_POST["email"];
    $pwd = $_POST["pwd"];
    $pwdRepeat = $_POST["pwdRepeat"];
    $dob = $_POST["dob"];

    // instantiate Signup controller class
    include "application/database/DatabaseHandler.php";
    include "application/class/controllers/SignupController.php";
    include "application/class/controllers/SignupController.php";

    $signup = new Signup($uid, $email, $pwd, $pwdRepeat, $dob);

    // running error handlers and user signup
    $signup->signupUser();

    // going back to login page
    header("location: " . root . "/login?error=none");
}