<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Error 404</title>
    <link rel="shortcut icon" type="image/x-icon" href="../images/favicon.svg" />
    <link rel="stylesheet" href="frontend/stylesheets/style-error404.css">
</head>
<body>

<div class="err404">
        <img id="err404-img" src="frontend/images/404error_page/spilled_drink_man.svg" alt="Spilled drink">
        <a href='/BackendRouting/login'>Back to login page</a>
</div>

</body>
</html>